### ISSUE TITLE
Plugin Commands

### ISSUE THREAD

**Issue by ShadowJonathan** [DrMeepso/CovePlugins#9]
Have plugins have the ability to register terminal commands, or at least receive inputted commands under `!<one_word_plugin_name> ...`, so that it can handle them itself.

**Comment by DrMeepso** [comment]
Im planning to add a registerCommand function to the plugin class that will allow it to be called from both the command line and the chat

**Comment by DrMeepso** [comment]
Just added that command api, you can see an example in [PersistentChalk.cs](https://github.com/DrMeepso/CovePlugins/blob/main/PersistentChalk/PersistentChalk.cs)!
